Shoppie/Controllers/AppUserController.cs
using Shoppie.Business.Services.Interfaces;
using Shoppie.Business.ViewModels;
using Shoppie.DataAccess.Entities;

namespace Shoppie.Controllers
{
    public class AppUserController : Controller
    {
        private readonly IUserService _userService;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public AppUserController(IUserService userService, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userService = userService;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Management()
        {
            var users = await _userService.GetUsersAsync();
            return View(users);
        }

        // GET: AppUserController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var user = await _userService.GetUserAsync(id);

            if (user is null)
                return NotFound();

            return View(user);
        }


        // GET: AppUserController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var user = await _userService.GetUserAsync(id);

            if (user is null)
                return NotFound();

            var model = new AppUserManagementVM
            {
                User = user,
            };

            return View(model);
        }

        // POST: AppUserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AppUserManagementVM model)
        {
            var user = await _userManager.FindByIdAsync(model.User.Id);

            if (user is null)
                return NotFound();

            await _userService.UpdateUserAsync(model);


            await _signInManager.RefreshSignInAsync(user);

            return RedirectToAction("Index", "Offer");
        }

        // GET: AppUserController/Delete/5
        public async Task<ActionResult> Delete(string id)
        {

            var user = await _userService.GetUserAsync(id);
            return View(user);
        }

        // POST: AppUserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, IFormCollection collection)
        {
            try
            {
                var result = await _userService.DeleteUserAsync(id);
                if (!result)
                {
                    throw new InvalidOperationException("Problem with deleting user");
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Shoppie/Controllers/CategoryController.cs
using Shoppie.Business.Services.Interfaces;

namespace Shoppie.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICategoryService _categoryService;

        public CategoryController(ILogger<HomeController> logger, ICategoryService categoryService)
        {
            _logger = logger;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Management()
        {
            var categories = await _categoryService.GetAllCategoriesAsync();

            return View(categories);
        }

        public async Task<IActionResult> Disable(int id)
        {
            var category = await _categoryService.GetCategoryAsync(id);

            if (category is null)
                return NotFound();
            else
                await _categoryService.DisableCategoryAsync(category);

            return RedirectToAction(nameof(Management));
        }

        public async Task<IActionResult> Enable(int id)
        {
            var category = await _categoryService.GetCategoryAsync(id);

            if (category is null)
                return NotFound();
            else
                await _categoryService.EnableCategoryAsync(category);

            return RedirectToAction(nameof(Management));
        }
    }
}

Shoppie/Controllers/OfferController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Shoppie.Business.Generators.Interfaces;
using Shoppie.Business.Services.Interfaces;
using Shoppie.Business.ViewModels;
using Shoppie.DataAccess;
using Shoppie.DataAccess.Entities;

namespace Shoppie.Controllers
{
    public class OfferController : Controller
    {
        private readonly IOfferService _offerService;
        private readonly ICategoryService _categoryService;
        private readonly IPdfGenerator _generator;
        private readonly ApplicationDbContext _context;
        private readonly ICookieService _cookieService;
        private readonly INBPIntegratorService _nbpIntegratorService;
        private readonly UserManager<AppUser> _userManager;

        public OfferController(IOfferService offerService, ICategoryService categoryService,
            ApplicationDbContext context, IPdfGenerator generator, ICookieService cookieService,
            INBPIntegratorService nbpIntegratorService, UserManager<AppUser> userManager)
        {
            _offerService = offerService;
            _categoryService = categoryService;
            _context = context;
            _generator = generator;
            _cookieService = cookieService;
            _nbpIntegratorService = nbpIntegratorService;
            _userManager = userManager;
        }

        // GET: Offer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _offerService.GetOfferAsync(id);

            if (offer is null)
            {
                return NotFound();
            }


            return View(offer);
        }

        // GET: Offer/Create
        [Authorize(Roles = $"Administrator")]
        public async Task<IActionResult> Create()
        {
            OfferVM offervM = new();

            var categories = await _categoryService.GetAllCategoriesAsync();

            ViewData["CategoryId"] = new SelectList(categories, "Id", "Name", offervM.CategoryId);
            return View(offervM);
        }

        // POST: Offer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"Administrator")]
        public async Task<IActionResult> Create(OfferVM vM)
        {
            if (vM.Image is null)
            {
                ModelState.AddModelError(nameof(vM.Image), "Please add an image");
            }

            if (!ModelState.IsValid)
            {
                var categories = await _categoryService.GetAllCategoriesAsync();

                ViewData["CategoryId"] = new SelectList(categories, "Id", "Name", vM.CategoryId);
                return View(vM);
            }

            await _offerService.AddOfferAsync(vM);

            return RedirectToAction(nameof(Index), "Home");
        }

        public IActionResult AddToCart(int id)
        {
            return RedirectToAction("Index");
        }

        // GET: Offer/Edit/5
        [Authorize(Roles = $"Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var offer = await _offerService.GetOfferAsync(id);

            if (offer is null)
            {
                return NotFound();
            }

            var categories = await _categoryService.GetAllCategoriesAsync();


            ViewData["CategoryId"] = new SelectList(categories, "Id", "Name");
            return View(offer);
        }

        // POST: Offer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"Administrator")]
        public async Task<IActionResult> Edit(OfferVM offer)
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", offer.CategoryId);

            if (offer.Image is null && offer.ImagePath is null)
            {
                ModelState.AddModelError(nameof(offer.Image), "Please add an image");
            }

            if (ModelState.IsValid)
            {
                await _offerService.UpdateOfferAsync(offer);
                return View(offer);
            }

            return View(offer);
        }

        // GET: Offer/Delete/5
        [Authorize(Roles = $"Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
                return NotFound();

            var offer = await _offerService.GetOfferAsync(id);

            return offer is null ? NotFound() : View(offer);
        }

        // POST: Offer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _offerService.DeleteOfferAsync(id);
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = $"Administrator")]
        public async Task<IActionResult> Management()
        {
            if (TempData["categories"] is not null)
            {
                ModelState.AddModelError("categories", TempData["categories"].ToString());
            }

            var offers = await _offerService.GetAllOffersAsync();
            var categories = await _categoryService.GetAllCategoriesAsync();

            OfferManagementVM model = new()
            {
                Offers = offers,
                Categories = categories,
            };
            ViewBag.CategoriesSelectList = new SelectList(model.Categories, "Id", "Name");

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> GeneratePDF(int SelectedCategoryId)
        {
            var offers = await _offerService.GetOffersByCategoryIdAsync(SelectedCategoryId);

            if (offers.Count == 0)
            {
                TempData["categories"] = "Cannot generate PDF for category with no associated offers";
                return RedirectToAction(nameof(Management));
            }

            string c = "euro";

            return _generator.GeneratePdf(offers);
        }
    }
}

Shoppie/Views/Shared/_CurrencyTab.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}




<div class="currency-bar"> 
        <div class="currency-bar-text">
            <p>Change currency: </p>            
        </div>
        <div class="currency-flag-box">
        <a asp-action="ChangeCurrency" asp-route-prefix="PLN">
                <img src="https://img.icons8.com/fluency/25/null/poland-circular.png" alt="Polish flag" title="PLN" />
            </a>
        </div>
        <div class="currency-flag-box">
        <a asp-action="ChangeCurrency" asp-route-prefix="USD">
            <img src="https://img.icons8.com/fluency/25/null/usa-circular.png" alt="US flag" title="$" />
        </a>
        </div>
        <div class="currency-flag-box">
        <a asp-action="ChangeCurrency" asp-route-prefix="EUR">
            <img src="https://img.icons8.com/fluency/25/null/european-union-circular-flag.png" alt="EU flag" title="€" />
        </a>
        </div>
</div>



@{
    //<a target="_blank" href="https://icons8.com/icon/Y76SzpmxslW4/european-union-circular-flag">European Union Circular Flag icon by Icons8</a>
    //<a target="_blank" href="https://icons8.com/icon/fIgZUHgwc76e/usa">Usa icon by Icons8</a>
    //<a target="_blank" href="https://icons8.com/icon/civsLZTDrVTT/poland">Poland icon by Icons8</a>
        
}

Shoppie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shoppie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shoppie.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
</head>
<body>
    <header class="header">
        <nav>          
            <ul >
                <li>                    
                    <a asp-area="" asp-controller="Home" asp-action="Index">Shoppie</a>
                </li>
                <li >
                    <a  asp-area="" asp-controller="Home" asp-action="Discount">Discounts</a>
                </li>
                <li>
                    <a  asp-area="" asp-controller="Home" asp-action="New">Recenlty added</a>
                </li>
                <li>
                    <partial name="_ManagmentPartial" />
                </li>
                <li>
                    <partial name="_LoginPartial" />
                </li>
                <li>
                    <a id="nav-cart" asp-controller="Home" asp-action="Cart">
                        <i class="bi bi-cart2"></i>
                        <span> 0</span>
                    </a>
                </li>
            </ul>

        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer-container">
        <nav>
            <div class="fotoer-sec">
                &copy; 2022 - Shoppie - 
                <a class="footer-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </nav>
        <nav>
            <div class="footer-section">
                <i class="bi bi-github"></i> 
                <a class="footer-link" href="https://github.com/fetus-elitus">
                    My Github
                </a>
            </div>
        </nav>
        <nav>
            <div class="footer-section">
                <a class="footer-link" href="https://microcorruption.com/map">Microc</a>
            </div>
        </nav>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shoppie/Views/Shared/_ManagmentPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Shoppie.Business.Seeders.Enums;
@using Shoppie.DataAccess.Entities;

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

@if (SignInManager.IsSignedIn(User) && User.IsInRole(Roles.Administrator.ToString()))
{
    <li >
        <a asp-controller="Offer" asp-action="Management">Offers Control Panel</a>
    </li>   
    <li>
        <a asp-controller="Category" asp-action="Management">Categories Control Panel</a>
    </li>
    <li>
        <a asp-controller="AppUser" asp-action="Management">Users Control Panel</a>
    </li>
}

Shoppie/Views/Shared/_OffersPartial.cshtml
@model IEnumerable<OfferVM>

<div class="products-container-grid">
    @foreach (var item in Model)
    {
        <div class="grid-item">
            <div class="products-image-box">
                <img src="/Images/1.jpg" />
                @if (item.Discount > 0)
                {
                    <div class="discount-badge">
                        <p>-@item.Discount%</p>
                    </div>
                }
            </div>
            <div class="products-text-nested-container">
                <div class="products-title-box">
                    <h3>@item.Title</h3>
                </div>
                <div>
                    <p>@item.Description</p>
                </div>
            </div>
            <div class="products-side-nested-container">
                <div class="products-price-box">
                    <p>@item.Price Zł</p>
                </div>
                <div class="products-addtocart-box">
                    <form asp-controller="Cart" asp-action="AddToCart">
                        <button class="btn-cart" type="submit">
                            <i class="bi bi-cart2">
                            Add to cart</i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    }
</div>

Shoppie/Views/Shared/_PaginationBarPartial.cshtml
@model PaginationModel

<div class="pagination-wrapper">
    <ul class="pagination pagination-sm">       
        @for (var pageNr = Model.StartPage; pageNr <= Model.EndPage; pageNr++)
        {
            <li class="custom-page-item">
                <a class="custom-page-link" asp-action="@Model.Action"
                   asp-route-pageNr="@pageNr"
                   data-index="@pageNr" >
                   @pageNr 
                </a>
            </li>
        }
    </ul>
</div>